version: '2'
services:
  service:
    image: qingmo/lightink-server:latest
    container_name: lightink-server
    environment:
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m -Dspring.profiles.active=prod
      - logDir=/app/log
    ports:
      - "9010:8080"
    volumes:
      - /app/log/qingmo:/log
